image: docker:stable

services:
  - docker:stable-dind

variables:
  CI_APPLICATION_REPOSITORY: "registry.gitlab.com/aroth/docker-security-scanning"
  CI_APPLICATION_TAG: $CI_COMMIT_SHA
  CI_APPLICATION_NAME: "tomcat-security-scanned"

stages:
  - build
  - test
  - deploy

## Build a docker container and pass it to the next stage
build:
  stage: build
  script:
    - docker build -t ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_NAME}-${CI_APPLICATION_TAG} . 
    - mkdir image_cache
    - docker save ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_NAME}-${CI_APPLICATION_TAG} > image_cache/cached_image.tar    
  artifacts:
    paths:
      - image_cache

# Perform security scan with clair
clair_scanning:
  stage: test
  script:
    - docker load -i image_cache/cached_image.tar
    - docker run -d --name db arminc/clair-db:latest
    - docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
    - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
    - mv clair-scanner_linux_amd64 clair-scanner
    - chmod +x clair-scanner
    - touch clair-whitelist.yml
    - while( ! wget -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; done
    - retries=0
    - echo "Waiting for clair daemon to start"
    - while( ! wget -T 10 -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
    - ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_NAME}-${CI_APPLICATION_TAG} || true
  artifacts:    
    paths: [gl-container-scanning-report.json, image_cache]

docker_bench_scanning:
  stage: test
  script:
    - docker run -it –net host –pid host –cap-add audit_control -v /var/lib:/var/lib -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc –label docker_bench_security docker/docker-bench-security
    - git clone https://github.com/docker/docker-bench-security.git 
    - cd docker-bench-security 
    - sh docker-bench-security.sh
  artifacts:    
    paths: [image_cache]

container_deploy:
  stage: deploy
  script:
    - docker load -i image_cache/cached_image.tar
    - docker login registry.gitlab.com -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}
    ## deactivated push becaue of a bug in gitlab
    #- docker push ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_NAME}-${CI_APPLICATION_TAG} 