image: docker:stable

services:
  - docker:stable-dind

variables:
  CI_APPLICATION_REPOSITORY: "apmregistry.azurecr.io"
  CI_APPLICATION_NAME: "tomcat-security-scanned"
  CI_DOCKER_IMAGE_NAME: ${CI_APPLICATION_REPOSITORY}/${CI_APPLICATION_NAME}:$CI_COMMIT_SHA

stages:
  - build
  - test
  - deploy

## Build a docker container and pass it to the next stage
build:
  stage: build
  script:
    - docker build -t ${CI_DOCKER_IMAGE_NAME} . 
    - mkdir image_cache
    - docker save ${CI_DOCKER_IMAGE_NAME} > image_cache/cached_image.tar    
  artifacts:
    paths:
      - image_cache

# Perform security scan with clair
clair_scanning:
  stage: test
  script:
    - docker load -i image_cache/cached_image.tar
    - docker run -d --name db arminc/clair-db:latest
    - docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
    - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
    - mv clair-scanner_linux_amd64 clair-scanner
    - chmod +x clair-scanner
    - touch clair-whitelist.yml
    - while( ! wget -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; done
    - retries=0
    - echo "Waiting for clair daemon to start"
    - while( ! wget -T 10 -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
    - ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${CI_DOCKER_IMAGE_NAME} || true
  artifacts:    
    paths: [gl-container-scanning-report.json, image_cache]

# Perform some dagda scan
#dagda_scanning:
#  stage: test
#  script:
#    - docker pull mongo
#    - docker run -d -p 27017:27017 mongo
#    - export DAGDA_PORT=5000
#    - export DAGDA_HOST='127.0.0.1'
#    - export VULNDB_HOST='127.0.0.1'
#    - export VULNDB_PORT=27017
#    - docker run -p $DAGDA_PORT:$DAGDA_PORT -v /var/run/docker.sock:/var/run/docker.sock:ro -v /tmp:/tmp:ro 3grander/dagda:0.7.0 start -s $DAGDA_HOST -p $DAGDA_PORT -m $VULNDB_HOST -mp $VULNDB_PORT
#    - docker run -e DAGDA_HOST=$DAGDA_HOST -e DAGDA_PORT=$DAGDA_PORT 3grander/dagda:0.7.0 vuln --init_status
#    - docker run -e DAGDA_HOST=$DAGDA_HOST -e DAGDA_PORT=$DAGDA_PORT 3grander/dagda:0.7.0 check --docker_umage ${CI_DOCKER_IMAGE_NAME} 
#  artifacts:    
#    paths: 
#      - image_cache

# Deploy to registry
container_deploy:
  stage: deploy
  script:
    - docker load -i image_cache/cached_image.tar
    - docker login apmregistry.azurecr.io -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}    
    - docker push ${CI_DOCKER_IMAGE_NAME} 